
var languageModule = angular.module('language', ['schoolERPCommon'])
    .config(function ($routeProvider, $locationProvider) {
   
        $routeProvider.when(schoolERP.rootPath + 'core/language', { templateUrl: schoolERP.rootPath + 'app/core/views/languagelist.html', controller: 'LanguageListViewModel' });
		$routeProvider.when(schoolERP.rootPath + 'core/language/languageedit/:languageId', { templateUrl: schoolERP.rootPath + 'app/core/views/languageedit.html', controller: 'LanguageEditViewModel' });
		
        $routeProvider.otherwise({ redirectTo: schoolERP.rootPath + 'core/language' });

		$locationProvider.html5Mode({
		  enabled: true,
		  requireBase: false
		});
    });

languageModule.controller("LanguageViewModel", function ($scope, $window, viewModelHelper) {

    $scope.viewModelHelper = viewModelHelper;

    $scope.previous = function () {
        $window.history.back();
    }
});

languageModule.controller("LanguageListViewModel", function ($scope,$window, $location, viewModelHelper) {

    $scope.previous = function () {
        $window.history.back();
    }

	$scope.title = 'Languages';
    $scope.viewMode = 'languagelist'; // languagelist, success
    $scope.modules = [];
   
    $scope.init = false; // used so view doesn't sit on "no available languages" while load takes place

    $scope.loadLanguages = function () {
        viewModelHelper.apiGet('api/language/availablelanguages', null,
                function (result) {
                    $scope.languages = result.data;
					if ($scope.init === false)
						initializeView();
                    $scope.init = true;
                });
    }

	var initializeView = function(){

	setTimeout(function () {
                
				var responsiveHelper_datatable_tabletools = undefined;

	var breakpointDefinition = {
            tablet: 1024,
            phone: 480
        };

	/* TABLETOOLS */
        var otable = $('#languageTable').DataTable({

            // Tabletools options:
            //   https://datatables.net/extensions/tabletools/button_options
            "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'l><'col-sm-6 col-xs-6 hidden-xs'T>r>" +
                    "t" +
                    "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
            "oTableTools": {
                "aButtons": [
                "copy",
                "csv",
                "xls",
                   {
                       "sExtends": "pdf",
                       "sTitle": "All Modules",
                       "sPdfMessage": "Eglobalicthub ERP PDF Export",
                       "sPdfSize": "letter"
                   },
                   {
                       "sExtends": "print",
                       "sMessage": "Generated by Eglobalicthub <i>(press Esc to close)</i>"
                   }
                ],
                "sSwfPath": "/Scripts/plugin/datatables/swf/copy_csv_xls_pdf.swf"
            },
            "autoWidth": true,
            "preDrawCallback": function () {
                // Initialize the responsive datatables helper once.
                if (!responsiveHelper_datatable_tabletools) {
                    responsiveHelper_datatable_tabletools = new ResponsiveDatatablesHelper($('#languageTable'), breakpointDefinition);
                }
            },
            "rowCallback": function (nRow) {
                responsiveHelper_datatable_tabletools.createExpandIcon(nRow);
            },
            "drawCallback": function (oSettings) {
                responsiveHelper_datatable_tabletools.respond();
            }
        });

		// custom toolbar
        //$("div.toolbar").html('<div class="text-right"><img src="/Content/img/logo.png" alt="SmartAdmin" style="width: 111px; margin-top: 3px; margin-right: 10px;"></div>');

        // Apply the filter
        $("#languageTable thead th input[type=text]").on('keyup change', function () {

            otable
                .column($(this).parent().index() + ':visible')
                .search(this.value)
                .draw();

        });

        /* END TABLETOOLS */

            }, 50);
	}

	$scope.createLanguage = function(){
	 $scope.viewMode = 'languageedit';
		$location.path(schoolERP.rootPath + 'core/language/languageedit/0');
	}

	$scope.viewLanguage = function(languageId){
	 $scope.viewMode = 'languageedit';
		$location.path(schoolERP.rootPath + 'core/language/languageedit/' + languageId);
	}

	$scope.deleteLanguage = function(languageId){
	    var deleteFlag = $window.confirm('Are you sure you want to delete this item.');

	    if (deleteFlag) {
	        viewModelHelper.apiPost('api/language/deletelanguage', languageId,
          function (result) {
              toastr.success('Item Deleted Successfully.', { closeButton: true, positionClass: 'toast-top-center', preventOPenDuplicates: true });
              $location.path(schoolERP.rootPath + 'core/language/languagelist');
          },
          function (result) {
              toastr.error('Fail to delete item', +result.data, { closeButton: true, positionClass: 'toast-top-center', preventOPenDuplicates: true });
              
          }, null);
	    }
	}

	$scope.languageStatus = function(state){
		if (state === true)
		return 'Active';
		return 'Not Active';
	}
  
    $scope.loadLanguages();
});

languageModule.controller("LanguageEditViewModel", function ($scope,$window, $location,$routeParams, viewModelHelper,validator) {



    viewModelHelper.modelIsValid = true;
    viewModelHelper.modelErrors = [];

	$scope.title = 'Edit Language';
    $scope.viewMode = 'languageedit'; // languagelist, success

    $scope.languageModel = {Code:'', Name:'' , Active:true};

	 $scope.languageRoleModels = [];
   
    $scope.init = false; // used so view doesn't sit on "no available languages" while load takes place

	 var languageModelRules = [];

    var setupRules = function () {
	languageModelRules.push(new validator.PropertyRule("Code", {
            required: { message: "Code is required" }
        }));

        languageModelRules.push(new validator.PropertyRule("Name", {
            required: { message: "Name is required" }
        }));
       
    }

	$scope.loadLanguage = function(){
	    if ($routeParams.languageId !== "0") {
	        viewModelHelper.apiGet('api/language/getlanguage/' + $routeParams.languageId, null,
						function (result) {
							$scope.languageModel = result.data;
							if ($scope.init === false)
								initializeView();
							$scope.init = true;
						});
			}
	}

	var initializeView = function(){
		setTimeout(function () {
                

            }, 50);
	}
	

	$scope.cancel = function(){
		$location.path(schoolERP.rootPath + 'core/language/languagelist');
	}

	$scope.save = function(){
		validator.ValidateModel($scope.languageModel, languageModelRules);
        viewModelHelper.modelIsValid = $scope.languageModel.isValid;
        viewModelHelper.modelErrors = $scope.languageModel.errors;
        if (viewModelHelper.modelIsValid) {

			viewModelHelper.apiPost('api/language/updatelanguage', $scope.languageModel,
            function (result) {
                toastr.success('Record Saved', { closeButton: true, positionClass: 'toast-top-center', preventOPenDuplicates: true });
                $location.path(schoolERP.rootPath + 'core/language/languagelist');
            }); 
        }
        else
            toastr.warning(viewModelHelper.modelErrors, 'Require Fields', { closeButton: true, positionClass: 'toast-top-center', preventOPenDuplicates: true });
	   
        $scope.$parent.viewModelHelper = viewModelHelper;
	}

	setupRules();
	$scope.loadLanguage();

});
