
var allAppModule = angular.module('allApp', ['schoolERPCommon'])
    .config(function ($routeProvider, $locationProvider) {
        $routeProvider.when(schoolERP.rootPath + 'core/module', { templateUrl: schoolERP.rootPath + 'app/core/views/allmodule.html', controller: 'ModuleListViewModel' });
        
        $routeProvider.otherwise({ redirectTo: schoolERP.rootPath + 'core/module' });

		$locationProvider.html5Mode({
		  enabled: true,
		  requireBase: false
		});

        //$locationProvider.html5Mode(true);
    });

allAppModule.controller("ModuleListViewModel", function ($scope, $http,$window, $location, viewModelHelper) {

    viewModelHelper.modelIsValid = true;
    viewModelHelper.modelErrors = [];

    $scope.viewMode = 'modulelist'; // modulelist, success
    $scope.modules = [];
   
    $scope.init = false; // used so view doesn't sit on "no available modules" while load takes place

    $scope.availableModules = function () {
        viewModelHelper.apiGet('api/module/availablemodules', null,
                function (result) {
                    $scope.modules = result.data;
					if ($scope.init === false)
						initializeView();
                    $scope.init = true;
                });
    }

	 $scope.previous = function () {
        $window.history.back();
	 }

	 $scope.moduleStatus = function (state) {
	     if (state === true)
	         return 'Active';
	     return 'Not Active';
	 }

	 $scope.activateModule = function (moduleId) {
        var deleteFlag = $window.confirm('Are you sure you want to activate this module.');

        if (deleteFlag) {
            viewModelHelper.apiPost('api/module/activatemodule', moduleId,
          function (result) {
              toastr.success('Module Activated Successfully.', { closeButton: true, positionClass: 'toast-top-center', preventOPenDuplicates: true });
              $location.path(schoolERP.rootPath + 'core/module/modulelist');
          },
          function (result) {
              toastr.error('Fail to activate module, ' + result.data, { closeButton: true, positionClass: 'toast-top-center', preventOPenDuplicates: true });
          }, null);
        }
    }

	 $scope.deactivateModule = function (moduleId) {
	     var deleteFlag = $window.confirm('Are you sure you want to de-activate this module.');

	     if (deleteFlag) {
	         viewModelHelper.apiPost('api/module/deactivatemodule', moduleId,
           function (result) {
               toastr.success('Module Deactivated Successfully.', { closeButton: true, positionClass: 'toast-top-center', preventOPenDuplicates: true });
               $location.path(schoolERP.rootPath + 'core/module/modulelist');
           },
           function (result) {
               toastr.error('Fail to deactivate module, ' + result.data, { closeButton: true, positionClass: 'toast-top-center', preventOPenDuplicates: true });
           }, null);
	     }
	 }

	var initializeView = function(){

	setTimeout(function () {
                
				var responsiveHelper_datatable_tabletools = undefined;

	var breakpointDefinition = {
            tablet: 1024,
            phone: 480
        };

	/* TABLETOOLS */
        var otable = $('#moduleTable').DataTable({

            // Tabletools options:
            //   https://datatables.net/extensions/tabletools/button_options
            "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'l><'col-sm-6 col-xs-6 hidden-xs'T>r>" +
                    "t" +
                    "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
            "oTableTools": {
                "aButtons": [
                "copy",
                "csv",
                "xls",
                   {
                       "sExtends": "pdf",
                       "sTitle": "All Modules",
                       "sPdfMessage": "Eglobalicthub ERP PDF Export",
                       "sPdfSize": "letter"
                   },
                   {
                       "sExtends": "print",
                       "sMessage": "Generated by Eglobalicthub <i>(press Esc to close)</i>"
                   }
                ],
                "sSwfPath": "/Scripts/plugin/datatables/swf/copy_csv_xls_pdf.swf"
            },
            "autoWidth": true,
            "preDrawCallback": function () {
                // Initialize the responsive datatables helper once.
                if (!responsiveHelper_datatable_tabletools) {
                    responsiveHelper_datatable_tabletools = new ResponsiveDatatablesHelper($('#moduleTable'), breakpointDefinition);
                }
            },
            "rowCallback": function (nRow) {
                responsiveHelper_datatable_tabletools.createExpandIcon(nRow);
            },
            "drawCallback": function (oSettings) {
                responsiveHelper_datatable_tabletools.respond();
            }
        });

		// custom toolbar
        //$("div.toolbar").html('<div class="text-right"><img src="/Content/img/logo.png" alt="SmartAdmin" style="width: 111px; margin-top: 3px; margin-right: 10px;"></div>');

        // Apply the filter
        $("#moduleTable thead th input[type=text]").on('keyup change', function () {

            otable
                .column($(this).parent().index() + ':visible')
                .search(this.value)
                .draw();

        });

        /* END TABLETOOLS */

            }, 50);
	}
  
	$scope.availableModules();

});
