
var roleRole = angular.module('role', ['schoolERPCommon'])
    .config(function ($routeProvider, $locationProvider) {
        $routeProvider.when(schoolERP.rootPath + 'core/role', { templateUrl: schoolERP.rootPath + 'app/core/views/role.html', controller: 'RoleListViewModel' });
        
        $routeProvider.otherwise({ redirectTo: schoolERP.rootPath + 'core/role' });

		$locationProvider.html5Mode({
		  enabled: true,
		  requireBase: false
		});
    });

roleRole.controller("RoleListViewModel", function ($scope, $http,$window, $location, viewModelHelper) {

    viewModelHelper.modelIsValid = true;
    viewModelHelper.modelErrors = [];

    $scope.viewMode = 'rolelist'; // rolelist, success
    $scope.roles = [];
   
    $scope.init = false; // used so view doesn't sit on "no available roles" while load takes place

    $scope.availableRoles = function () {
        viewModelHelper.apiGet('api/role/getroles', null,
                function (result) {
                    $scope.roles = result.data;
					if ($scope.init === false)
						initializeView();
                    $scope.init = true;
                });
    }

	 $scope.previous = function () {
        $window.history.back();
    }

	var initializeView = function(){

	setTimeout(function () {
                
				var responsiveHelper_datatable_tabletools = undefined;

	var breakpointDefinition = {
            tablet: 1024,
            phone: 480
        };

	/* TABLETOOLS */
        var otable = $('#roleTable').DataTable({

            // Tabletools options:
            //   https://datatables.net/extensions/tabletools/button_options
            "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'l><'col-sm-6 col-xs-6 hidden-xs'T>r>" +
                    "t" +
                    "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
            "oTableTools": {
                "aButtons": [
                "copy",
                "csv",
                "xls",
                   {
                       "sExtends": "pdf",
                       "sTitle": "All Roles",
                       "sPdfMessage": "Eglobalicthub ERP PDF Export",
                       "sPdfSize": "letter"
                   },
                   {
                       "sExtends": "print",
                       "sMessage": "Generated by Eglobalicthub <i>(press Esc to close)</i>"
                   }
                ],
                "sSwfPath": "/Scripts/plugin/datatables/swf/copy_csv_xls_pdf.swf"
            },
            "autoWidth": true,
            "preDrawCallback": function () {
                // Initialize the responsive datatables helper once.
                if (!responsiveHelper_datatable_tabletools) {
                    responsiveHelper_datatable_tabletools = new ResponsiveDatatablesHelper($('#roleTable'), breakpointDefinition);
                }
            },
            "rowCallback": function (nRow) {
                responsiveHelper_datatable_tabletools.createExpandIcon(nRow);
            },
            "drawCallback": function (oSettings) {
                responsiveHelper_datatable_tabletools.respond();
            }
        });

		// custom toolbar
        //$("div.toolbar").html('<div class="text-right"><img src="/Content/img/logo.png" alt="SmartAdmin" style="width: 111px; margin-top: 3px; margin-right: 10px;"></div>');

        // Apply the filter
        $("#roleTable thead th input[type=text]").on('keyup change', function () {

            otable
                .column($(this).parent().index() + ':visible')
                .search(this.value)
                .draw();

        });

        /* END TABLETOOLS */

            }, 50);
	}
  
    $scope.availableRoles();
});
